%% =======================================================================
%  SWOT vs ADCP GEOSTROPHIC VELOCITY FIGURE (FULL DAC) - PLOTTING ONLY
%  Reads 'swot_figure_inputs_DAC97_5.mat' generated by
%  compute_swot_adcp_inputs.py (DAC configuration).
%  SWOT correction = TIDE + REGIONAL DAC (IB + dynamic response).
%  Contrast figure against the IB version (Fig08).
%  Layout 2x2 | Times New Roman (20pt)
%    Row 1 (NEAR): (a) u_g/v_g series | (b) temporal sensitivity
%    Row 2 (N9)  : (c) u_g/v_g series | (d) temporal sensitivity
%  "0 km" is discarded at load time (as in the IB version); spatial_list
%  and the sensitivity matrices are defined for 30/60/90/120/150 km only.
%  Y-limits kept at [-7.5 7.5], same scale as the IB figure, for direct
%  visual contrast.
%% =======================================================================
clear; close all; clc;
OUT_DIR = './OSTST_Output_DAC';                 % does not overwrite OSTST_Output_IB
if ~exist(OUT_DIR, 'dir'), mkdir(OUT_DIR); end

%% 1. LOAD
MAT_FILE = 'swot_figure_inputs_DAC97_5.mat';
if ~exist(MAT_FILE, 'file')
    error('%s not found. Run compute_swot_adcp_inputs.py (DAC configuration) first.', MAT_FILE);
end
D = load(MAT_FILE);
% --- Exclude "0 km" at load time (defensive; the engine already excludes it) ---
spatial_list_full = D.spatial_list(:)';
mask_spat         = abs(spatial_list_full) > 1e-6;    % true for everything except 0 km
spatial_list      = spatial_list_full(mask_spat);
num_spat          = numel(spatial_list);
temporal_range = D.temporal_range(:)';
bn = D.near.best;   sens_near = D.near.sens_matrix(:, mask_spat);
b9 = D.n9.best;     sens_n9   = D.n9.sens_matrix(:, mask_spat);
tn = datetime(bn.t(:), 'ConvertFrom', 'datenum');
t9 = datetime(b9.t(:), 'ConvertFrom', 'datenum');
xn = [datetime(bn.xlim_min,'ConvertFrom','datenum'), datetime(bn.xlim_max,'ConvertFrom','datenum')];
x9 = [datetime(b9.xlim_min,'ConvertFrom','datenum'), datetime(b9.xlim_max,'ConvertFrom','datenum')];

%% 2. STYLE AND PALETTE (5 colours, no 0 km; same order as the IB figure)
FONT = 'Times New Roman';  FS = 20;  LW = 1.5;
cmap_dac = [196 196 196;   % 30 km
            126 222 214;   % 60 km
            195 147 255;   % 90 km
            253 154  95;   % 120 km
            250 223  90] / 255;  % 150 km
if size(cmap_dac,1) < num_spat
    cmap_dac = lines(num_spat);
end
COLOR_ZERO = cmap_dac(1, :);
COLOR_META = cmap_dac(1, :);
COLOR_UG   = cmap_dac(2, :);
COLOR_VG   = cmap_dac(3, :);

%% 3. GEOMETRY
fig = figure('Visible','off','Color','w','Units','pixels','Position',[50 50 1950 1050]);
margL = 0.085; gapX = 0.085;
width_col1 = 0.460; width_col2 = 0.325;
row1_y_bottom = 0.550; row2_y_bottom = 0.080; row_total_h = 0.390;
ts_subplot_h = 0.185; ts_inner_gap = 0.020;
yl_u = [-7.5 7.5];      % same scale as the IB figure for direct contrast
yl_v = [-7.5 7.5];

%% ================= ROW 1: NEAR =================
% (a) u_g
pos = [margL, row1_y_bottom + ts_subplot_h + ts_inner_gap, width_col1, ts_subplot_h];
ax = axes('Parent',fig,'Position',pos); hold(ax,'on'); box(ax,'on');
h1 = plot(ax, tn, bn.u_adcp, '-',  'Color', COLOR_UG, 'LineWidth', LW);
h2 = plot(ax, tn, bn.u_swot, ':',  'Color', COLOR_UG, 'LineWidth', LW);
hz = yline(ax, 0, '-', 'Color', COLOR_ZERO, 'LineWidth', 0.8); uistack(hz,'bottom');
ylabel(ax, 'u_g (cm/s)', 'FontName', FONT, 'FontSize', FS);
set(ax, 'XLim', xn, 'YLim', yl_u, 'XTickLabel', {}, 'FontName', FONT, 'FontSize', FS);
text(ax, 0.02, 0.875, sprintf('r = %.1f    RMSE = %.1f (cm/s)', bn.r_u, bn.rmse_u), 'Units','normalized', ...
    'FontName', FONT, 'FontSize', FS, 'BackgroundColor','w', 'EdgeColor','none', 'Margin', 4);
text(ax, 0.02, 0.12, sprintf('%d km | %d days | Barotropic layer | Tide+DAC (full)', bn.km, bn.days), 'Units','normalized', ...
    'FontName', FONT, 'FontSize', FS, 'Color', COLOR_META);
lg = legend(ax, [h1 h2], {'Aquadopp Gen-1','Geostrophic SWOT'}, 'Location','northeast','Orientation','horizontal');
set(lg, 'FontName', FONT, 'FontSize', FS, 'Box','on');
title(ax, '\bf(a)', 'FontName', FONT, 'FontSize', FS);
% (a) v_g
pos = [margL, row1_y_bottom, width_col1, ts_subplot_h];
ax = axes('Parent',fig,'Position',pos); hold(ax,'on'); box(ax,'on');
h3 = plot(ax, tn, bn.v_adcp, '-', 'Color', COLOR_VG, 'LineWidth', LW);
h4 = plot(ax, tn, bn.v_swot, ':', 'Color', COLOR_VG, 'LineWidth', LW);
hz = yline(ax, 0, '-', 'Color', COLOR_ZERO, 'LineWidth', 0.8); uistack(hz,'bottom');
ylabel(ax, 'v_g (cm/s)', 'FontName', FONT, 'FontSize', FS);
set(ax, 'XLim', xn, 'YLim', yl_v, 'XTickLabel', {}, 'FontName', FONT, 'FontSize', FS);
text(ax, 0.02, 0.875, sprintf('r = %.1f    RMSE = %.1f (cm/s)', bn.r_v, bn.rmse_v), 'Units','normalized', ...
    'FontName', FONT, 'FontSize', FS, 'BackgroundColor','w', 'EdgeColor','none', 'Margin', 4);
text(ax, 0.02, 0.12, sprintf('%d km | %d days | Barotropic layer | Tide+DAC (full)', bn.km, bn.days), 'Units','normalized', ...
    'FontName', FONT, 'FontSize', FS, 'Color', COLOR_META);
lg = legend(ax, [h3 h4], {'Aquadopp Gen-1','Geostrophic SWOT'}, 'Location','northeast','Orientation','horizontal');
set(lg, 'FontName', FONT, 'FontSize', FS, 'Box','on');
% (b) NEAR temporal sensitivity
pos = [margL + width_col1 + gapX, row1_y_bottom, width_col2, row_total_h];
ax = axes('Parent',fig,'Position',pos); hold(ax,'on'); box(ax,'on'); grid(ax,'on');
h_curves = gobjects(num_spat,1); leg_labels = cell(num_spat,1);
for s = 1:num_spat
    h_curves(s) = plot(ax, temporal_range, sens_near(:,s), 'o-', ...
        'Color', cmap_dac(s,:), 'MarkerFaceColor', cmap_dac(s,:), 'LineWidth', LW, 'MarkerSize', 6);
    leg_labels{s} = sprintf('%d km', spatial_list(s));
    [val, idx] = max(sens_near(:,s));
    if isfinite(val)
        plot(ax, temporal_range(idx), val, 'o', 'MarkerFaceColor', cmap_dac(s,:), ...
            'MarkerEdgeColor','k', 'LineWidth', 1.5, 'MarkerSize', 9);
    end
end
ylabel(ax, 'Max Correlation Score', 'FontName', FONT, 'FontSize', FS);
set(ax, 'XLim', [1.5 20.5], 'XTick', 2:2:20, 'XTickLabel', {}, 'YLim', [0.1 0.7], 'FontName', FONT, 'FontSize', FS);
title(ax, '\bf(b)', 'FontName', FONT, 'FontSize', FS);
lg = legend(ax, h_curves, leg_labels, 'Location','southeast', 'NumColumns', 2);
set(lg, 'FontName', FONT, 'FontSize', FS, 'Box','on');

%% ================= ROW 2: N9 =================
% (c) u_g
pos = [margL, row2_y_bottom + ts_subplot_h + ts_inner_gap, width_col1, ts_subplot_h];
ax = axes('Parent',fig,'Position',pos); hold(ax,'on'); box(ax,'on');
plot(ax, t9, b9.u_adcp, '-', 'Color', COLOR_UG, 'LineWidth', LW);
plot(ax, t9, b9.u_swot, ':', 'Color', COLOR_UG, 'LineWidth', LW);
hz = yline(ax, 0, '-', 'Color', COLOR_ZERO, 'LineWidth', 0.8); uistack(hz,'bottom');
ylabel(ax, 'u_g (cm/s)', 'FontName', FONT, 'FontSize', FS);
set(ax, 'XLim', x9, 'YLim', yl_u, 'XTickLabel', {}, 'FontName', FONT, 'FontSize', FS);
text(ax, 0.02, 0.875, sprintf('r = %.1f    RMSE = %.1f (cm/s)', b9.r_u, b9.rmse_u), 'Units','normalized', ...
    'FontName', FONT, 'FontSize', FS, 'BackgroundColor','w', 'EdgeColor','none', 'Margin', 4);
text(ax, 0.02, 0.12, sprintf('%d km | %d days | Barotropic layer | Tide+DAC (full)', b9.km, b9.days), 'Units','normalized', ...
    'FontName', FONT, 'FontSize', FS, 'Color', COLOR_META);
title(ax, '\bf(c)', 'FontName', FONT, 'FontSize', FS);
% (c) v_g
pos = [margL, row2_y_bottom, width_col1, ts_subplot_h];
ax = axes('Parent',fig,'Position',pos); hold(ax,'on'); box(ax,'on');
plot(ax, t9, b9.v_adcp, '-', 'Color', COLOR_VG, 'LineWidth', LW);
plot(ax, t9, b9.v_swot, ':', 'Color', COLOR_VG, 'LineWidth', LW);
hz = yline(ax, 0, '-', 'Color', COLOR_ZERO, 'LineWidth', 0.8); uistack(hz,'bottom');
ylabel(ax, 'v_g (cm/s)', 'FontName', FONT, 'FontSize', FS);
set(ax, 'XLim', x9, 'YLim', yl_v, 'FontName', FONT, 'FontSize', FS);
xtickformat(ax, 'dd-MMM');
text(ax, 0.02, 0.875, sprintf('r = %.1f    RMSE = %.1f (cm/s)', b9.r_v, b9.rmse_v), 'Units','normalized', ...
    'FontName', FONT, 'FontSize', FS, 'BackgroundColor','w', 'EdgeColor','none', 'Margin', 4);
text(ax, 0.02, 0.12, sprintf('%d km | %d days | Barotropic layer | Tide+DAC (full)', b9.km, b9.days), 'Units','normalized', ...
    'FontName', FONT, 'FontSize', FS, 'Color', COLOR_META);
% (d) N9 temporal sensitivity
pos = [margL + width_col1 + gapX, row2_y_bottom, width_col2, row_total_h];
ax = axes('Parent',fig,'Position',pos); hold(ax,'on'); box(ax,'on'); grid(ax,'on');
h_curves = gobjects(num_spat,1);
for s = 1:num_spat
    h_curves(s) = plot(ax, temporal_range, sens_n9(:,s), 'o-', ...
        'Color', cmap_dac(s,:), 'MarkerFaceColor', cmap_dac(s,:), 'LineWidth', LW, 'MarkerSize', 6);
    [val, idx] = max(sens_n9(:,s));
    if isfinite(val)
        plot(ax, temporal_range(idx), val, 'o', 'MarkerFaceColor', cmap_dac(s,:), ...
            'MarkerEdgeColor','k', 'LineWidth', 1.5, 'MarkerSize', 9);
    end
end
xlabel(ax, 'Gaussian Filter Cutoff (Days)', 'FontName', FONT, 'FontSize', FS);
ylabel(ax, 'Max Correlation Score', 'FontName', FONT, 'FontSize', FS);
set(ax, 'XLim', [1.5 20.5], 'XTick', 2:2:20, 'YLim', [0.1 0.7], 'FontName', FONT, 'FontSize', FS);
title(ax, '\bf(d)', 'FontName', FONT, 'FontSize', FS);
lg = legend(ax, h_curves, leg_labels, 'Location','southeast', 'NumColumns', 2);
set(lg, 'FontName', FONT, 'FontSize', FS, 'Box','on');

%% 4. EXPORT
base = fullfile(OUT_DIR, 'FigS3');
exportgraphics(fig, [base '.png'], 'Resolution', 600);
close(fig);
fprintf('\nDAC figure exported: %s.png\n', base);
